#!/usr/bin/env python3
"""
analizar_incremental_clases_impares.py

Análisis incremental de distribuciones α_c para clases impares (1,3,5,7,9).
Procesa de 10 en 10 hasta 100, luego de 100 en 100.
Guarda checkpoints y distribuciones acumulativas.

Estrategia:
- Clases impares: 1, 3, 5, 7, 9
- Lotes: 10, 20, 30, ..., 100, 200, 300, ...
- Alterna entre clases para balance
- Distribuciones acumulativas (todos los α_c hasta el momento)
- Solo mantiene últimos 10 checkpoints por clase

Uso:
    python analizar_incremental_clases_impares.py --device mps
"""
import os
import sys
import torch
import numpy as np
import argparse
from datetime import datetime
from tqdm import tqdm
import torchvision.transforms.functional as TF
from pathlib import Path
import json

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from kuramoto.modelo import KBlock
from datasets.loader import MNISTLoader


def get_device(device_arg='auto'):
    """Detecta el mejor dispositivo disponible."""
    if device_arg == 'auto':
        if torch.backends.mps.is_available():
            device = torch.device('mps')
            print("✅ Usando GPU: Metal Performance Shaders (MPS)")
        elif torch.cuda.is_available():
            device = torch.device('cuda')
            print(f"✅ Usando GPU: CUDA ({torch.cuda.get_device_name(0)})")
        else:
            device = torch.device('cpu')
            print("⚠️  Usando CPU (GPU no disponible)")
    else:
        device = torch.device(device_arg)
        print(f"✅ Usando dispositivo: {device_arg}")
    
    return device


def calcular_curva_imagen(kblock, img, alphas, ch=4, h=64, w=64, T=100, device='cpu'):
    """Calcula curva R(α) para una imagen."""
    # Preparar imagen
    if img.ndim == 3 and img.shape[0] == 1:
        img_single = img[0]
    else:
        img_single = img
    
    img_resized = TF.resize(img_single.unsqueeze(0), [h, w])[0]
    img_channels = img_resized.repeat(ch, 1, 1).to(device)
    
    order_params = []
    
    for alpha in alphas:
        with torch.no_grad():
            c_scaled = img_channels.unsqueeze(0) * alpha
            x0 = torch.randn(1, ch, h, w, device=device)
            
            x_final, xs, es = kblock(
                x0, c_scaled, T=T, gamma=0.7, del_t=0.9,
                return_xs=True, return_es=True
            )
            
            R_t = []
            for x_t in xs[-5:]:
                x_complex = torch.view_as_complex(
                    x_t[0, 0:2].permute(1, 2, 0).contiguous()
                )
                # Fix para MPS: torch.angle no soportado en MPS
                if x_complex.device.type == 'mps':
                    x_complex_cpu = x_complex.cpu()
                    phases = torch.angle(x_complex_cpu)
                else:
                    phases = torch.angle(x_complex)
                R = np.abs(np.mean(np.exp(1j * phases.cpu().detach().numpy())))
                R_t.append(R)
            
            R = np.mean(R_t)
            order_params.append(R)
    
    if device.type == 'mps':
        torch.mps.empty_cache()
    elif device.type == 'cuda':
        torch.cuda.empty_cache()
    
    return np.array(order_params)


def limpiar_checkpoints_antiguos(checkpoint_dir, clase, max_checkpoints=10):
    """Mantiene solo los últimos N checkpoints por clase."""
    pattern = f"checkpoint_clase{clase}_*.pt"
    checkpoints = sorted(checkpoint_dir.glob(pattern))
    
    if len(checkpoints) > max_checkpoints:
        # Eliminar los más antiguos
        for ckpt in checkpoints[:-max_checkpoints]:
            ckpt.unlink()
            print(f"  🗑️  Eliminado checkpoint antiguo: {ckpt.name}")


def guardar_checkpoint(data, checkpoint_dir, clase, n_imgs):
    """Guarda checkpoint para una clase."""
    checkpoint_dir.mkdir(exist_ok=True, parents=True)
    
    checkpoint_file = checkpoint_dir / f"checkpoint_clase{clase}_{n_imgs:04d}imgs.pt"
    torch.save(data, checkpoint_file)
    
    # Limpiar checkpoints antiguos
    limpiar_checkpoints_antiguos(checkpoint_dir, clase, max_checkpoints=10)
    
    return checkpoint_file


def cargar_checkpoints(checkpoint_dir, clases_impares):
    """Carga checkpoints existentes para todas las clases impares."""
    estado = {}
    
    for clase in clases_impares:
        # Buscar el checkpoint más reciente
        pattern = f"checkpoint_clase{clase}_*.pt"
        checkpoints = sorted(checkpoint_dir.glob(pattern))
        
        if checkpoints:
            ultimo_ckpt = checkpoints[-1]
            # For compatibility with PyTorch >=2.6 safe loading, force full load of our own checkpoints
            # (these checkpoints are generated by this project and are trusted).
            try:
                data = torch.load(ultimo_ckpt, map_location='cpu', weights_only=False)
            except TypeError:
                # Older PyTorch versions may not support weights_only arg
                data = torch.load(ultimo_ckpt, map_location='cpu')
            estado[clase] = data
            print(f"  ✅ Clase {clase}: Cargado checkpoint con {data['n_imgs']} imágenes")
        else:
            estado[clase] = None
            print(f"  ℹ️  Clase {clase}: Sin checkpoint previo, empezando desde cero")
    
    return estado


def calcular_distribucion_acumulativa(estado, output_dir, n_total_por_clase):
    """Genera distribución acumulativa con todos los α_c hasta el momento."""
    print("\n" + "="*70)
    print("GENERANDO DISTRIBUCIÓN ACUMULATIVA")
    print("="*70)
    
    clases_impares = sorted(estado.keys())
    
    # Recopilar todos los α_c
    distribucion = {
        'clases_impares': clases_impares,
        'alphas_c': {},
        'estadisticas': {},
        'timestamp': datetime.now().isoformat(),
        'n_imgs_por_clase': {}
    }
    
    for clase in clases_impares:
        if estado[clase] is not None:
            alphas_c = estado[clase]['alphas_c']
            distribucion['alphas_c'][clase] = alphas_c
            distribucion['n_imgs_por_clase'][clase] = len(alphas_c)
            
            # Estadísticas
            distribucion['estadisticas'][clase] = {
                'mean': float(np.mean(alphas_c)),
                'std': float(np.std(alphas_c)),
                'median': float(np.median(alphas_c)),
                'min': float(np.min(alphas_c)),
                'max': float(np.max(alphas_c)),
                'n': len(alphas_c)
            }
            
            stats = distribucion['estadisticas'][clase]
            print(f"\nClase {clase} ({stats['n']} imágenes):")
            print(f"  α_c: {stats['mean']:.6f} ± {stats['std']:.6f}")
            print(f"  Rango: [{stats['min']:.6f}, {stats['max']:.6f}]")
    
    # Guardar distribución
    output_dir.mkdir(exist_ok=True, parents=True)
    dist_file = output_dir / f"distribucion_acumulativa_{n_total_por_clase:04d}imgs.pt"
    torch.save(distribucion, dist_file)
    print(f"\n✅ Distribución guardada: {dist_file.name}")
    
    return distribucion


def generar_secuencia_lotes(max_imgs=6000):
    """Genera secuencia: 10, 20, 30, ..., 100, 200, 300, ..."""
    lotes = []
    
    # De 10 en 10 hasta 100
    for n in range(10, 101, 10):
        lotes.append(n)
    
    # De 100 en 100 hasta max_imgs
    n = 200
    while n <= max_imgs:
        lotes.append(n)
        n += 100
    
    return lotes


def main(args):
    start_time = datetime.now()
    
    print("="*70)
    print("ANÁLISIS INCREMENTAL - TODAS LAS CLASES")
    print("="*70)
    print(f"Inicio: {start_time.strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Clases a procesar: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9")
    print()
    
    # Configuración
    device = get_device(args.device)
    clases_impares = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
    ch, n, h, w, T = 4, 4, 64, 64, 100
    
    # Directorios
    checkpoint_dir = Path(args.checkpoint_dir)
    output_dir = Path(args.output_dir)
    
    # Cargar checkpoints existentes
    print("\n" + "="*70)
    print("CARGANDO CHECKPOINTS EXISTENTES")
    print("="*70)
    estado = cargar_checkpoints(checkpoint_dir, clases_impares)
    
    # Inicializar estado si es necesario
    for clase in clases_impares:
        if estado[clase] is None:
            estado[clase] = {
                'clase': clase,
                'n_imgs': 0,
                'alphas_c': [],
                'ultimo_idx_procesado': -1
            }
    
    # Cargar dataset
    print("\n" + "="*70)
    print("CARGANDO DATASET - TRAIN SET")
    print("="*70)
    mn = MNISTLoader(root=args.data_root, batch_size=1, img_size=64)
    train_loader, _ = mn.get_mnist(batch_size=1, train_split=True)
    
    # Organizar imágenes por clase
    print("Organizando imágenes por clase (TRAIN SET)...")
    images_by_class = {i: [] for i in clases_impares}
    
    for img_batch, label_batch in train_loader:
        label = int(label_batch[0].item())
        if label in clases_impares:
            images_by_class[label].append(img_batch[0])
        
        # Verificar si ya tenemos suficientes
        if all(len(images_by_class[c]) >= args.max_imgs_per_class for c in clases_impares):
            break
    
    for clase in clases_impares:
        print(f"  Clase {clase}: {len(images_by_class[clase])} imágenes disponibles")
    
    # Modelo
    print(f"\nInicializando modelo en {device}...")
    kblock = KBlock(n=n, ch=ch, T=100, ksize=7, init_omg=0.1).to(device)
    
    # Array de alphas
    alphas = np.arange(args.alpha_min, args.alpha_max + args.alpha_step/2, args.alpha_step)
    print(f"\nRango α: [{alphas[0]:.6f}, {alphas[-1]:.6f}], {len(alphas)} puntos")
    
    # Generar secuencia de lotes
    secuencia_lotes = generar_secuencia_lotes(args.max_imgs_per_class)
    print(f"\nSecuencia de lotes: {secuencia_lotes[:15]}{'...' if len(secuencia_lotes) > 15 else ''}")
    
    # Procesamiento incremental
    print("\n" + "="*70)
    print("INICIO DE PROCESAMIENTO INCREMENTAL")
    print("="*70)
    
    for target_n in secuencia_lotes:
        print(f"\n{'='*70}")
        print(f"OBJETIVO: {target_n} imágenes por clase")
        print(f"{'='*70}")
        
        # Procesar cada clase impar en orden
        for clase in clases_impares:
            n_actual = estado[clase]['n_imgs']
            
            if n_actual >= target_n:
                print(f"\n✓ Clase {clase}: Ya tiene {n_actual} imágenes (≥{target_n}), saltando...")
                continue
            
            # Calcular cuántas imágenes nuevas procesar
            n_nuevas = target_n - n_actual
            idx_inicio = estado[clase]['ultimo_idx_procesado'] + 1
            idx_fin = idx_inicio + n_nuevas
            
            print(f"\n{'─'*70}")
            print(f"Procesando Clase {clase}: imágenes {idx_inicio} a {idx_fin-1}")
            print(f"{'─'*70}")
            
            # Verificar disponibilidad
            if idx_fin > len(images_by_class[clase]):
                print(f"⚠️  Solo {len(images_by_class[clase])} disponibles, ajustando...")
                idx_fin = len(images_by_class[clase])
                n_nuevas = idx_fin - idx_inicio
            
            if n_nuevas <= 0:
                continue
            
            # Procesar imágenes nuevas
            nuevos_alphas_c = []
            
            with tqdm(total=n_nuevas, desc=f"Clase {clase}") as pbar:
                for img_idx in range(idx_inicio, idx_fin):
                    img = images_by_class[clase][img_idx]
                    
                    # Calcular curva
                    order_params = calcular_curva_imagen(
                        kblock, img, alphas,
                        ch=ch, h=h, w=w, T=T, device=device
                    )
                    
                    # Calcular α_c
                    dR = np.gradient(order_params, alphas)
                    alpha_c = alphas[np.argmax(dR)]
                    nuevos_alphas_c.append(alpha_c)
                    
                    pbar.update(1)
                    pbar.set_postfix({'α_c': f'{alpha_c:.5f}'})
            
            # Actualizar estado
            estado[clase]['alphas_c'].extend(nuevos_alphas_c)
            estado[clase]['n_imgs'] = len(estado[clase]['alphas_c'])
            estado[clase]['ultimo_idx_procesado'] = idx_fin - 1
            
            # Guardar checkpoint cada 100 imágenes procesadas por clase, o al terminar la clase
            n_imgs_actual = estado[clase]['n_imgs']
            total_disponibles = len(images_by_class[clase])
            if (n_imgs_actual % 100 == 0) or (n_imgs_actual == total_disponibles):
                checkpoint_file = guardar_checkpoint(
                    estado[clase], 
                    checkpoint_dir, 
                    clase, 
                    estado[clase]['n_imgs']
                )
                print(f"  💾 Checkpoint guardado: {checkpoint_file.name}")
            else:
                print(f"  (No se guarda checkpoint: {n_imgs_actual} imágenes, próximo guardado a {(n_imgs_actual//100+1)*100}.)")
        
        # Generar distribución acumulativa
        calcular_distribucion_acumulativa(estado, output_dir, target_n)
        
        # Pausa para verificar si continuar
        if target_n == 100:
            print("\n" + "="*70)
            print("⏸️  PUNTO DE VERIFICACIÓN: 100 imágenes por clase completadas")
            print("="*70)
            print("Presiona Ctrl+C para detener, o espera 10 segundos para continuar...")
            
            import time
            try:
                time.sleep(10)
            except KeyboardInterrupt:
                print("\n\n⚠️  Proceso pausado por el usuario")
                break
    
    # Resumen final
    end_time = datetime.now()
    duration = (end_time - start_time).total_seconds()
    
    print("\n" + "="*70)
    print("RESUMEN FINAL")
    print("="*70)
    
    total_imgs = sum(estado[c]['n_imgs'] for c in clases_impares)
    print(f"Total de imágenes procesadas: {total_imgs}")
    print(f"Duración total: {duration/60:.1f} minutos")
    print(f"Tiempo por imagen: {duration/total_imgs:.2f} segundos" if total_imgs > 0 else "")
    
    for clase in clases_impares:
        print(f"  Clase {clase}: {estado[clase]['n_imgs']} imágenes")
    
    print("\nCheckpoints guardados en:", checkpoint_dir)
    print("Distribuciones guardadas en:", output_dir)
    print()


if __name__ == '__main__':
    parser = argparse.ArgumentParser(
        description='Análisis incremental de clases impares con checkpoints',
        formatter_class=argparse.ArgumentDefaultsHelpFormatter
    )
    
    parser.add_argument('--max_imgs_per_class', type=int, default=6000,
                       help='Máximo de imágenes por clase a procesar')
    parser.add_argument('--checkpoint_dir', default='checkpoints_incremental',
                       help='Directorio para checkpoints')
    parser.add_argument('--output_dir', default='distribuciones_incrementales',
                       help='Directorio para distribuciones acumulativas')
    
    # Rango de alpha
    parser.add_argument('--alpha_min', type=float, default=0.0)
    parser.add_argument('--alpha_max', type=float, default=0.1)
    parser.add_argument('--alpha_step', type=float, default=0.0005)
    
    # Configuración
    parser.add_argument('--data_root', default='./data')
    parser.add_argument('--device', default='auto',
                       choices=['auto', 'mps', 'cuda', 'cpu'])
    
    args = parser.parse_args()
    
    try:
        main(args)
    except KeyboardInterrupt:
        print("\n\n⚠️  Proceso interrumpido por el usuario")
        sys.exit(0)
    except Exception as e:
        print(f"\n\n❌ Error: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
